react_native_path = '../node_modules/react-native'
platform :ios, '10.0'

target 'ChatOnReact' do
    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'yoga', :path => react_native_path + '/ReactCommon/yoga'

    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => react_native_path + '/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
    
    pod 'React', :path => react_native_path, :subspecs => [
      'Core',
      'CxxBridge',
      'RCTText',
      'RCTImage',
      'RCTAnimation',
      'RCTLinkingIOS',
      'DevSupport',
      'RCTNetwork',
      'RCTWebSocket'
    ]

    pod 'CENNotifications', :path => '../node_modules/chat-engine-notifications'
end
